# Generated by Django 3.2.3 on 2021-06-05 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='CREATED_AT',
            new_name='created_at',
        ),
    ]
