# Generated by Django 4.0.1 on 2022-01-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='priorty',
            new_name='priority',
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('inprogress', 'In progress'), ('lost', 'Lost'), ('won', 'Won')], default='new', max_length=25),
        ),
    ]
